In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import config
import os

In [2]:
# data_2022 = pd.read_csv(os.path.join('data',"resultats-par-niveau-burvot-t1-france-entiere.txt"),sep=';',encoding='latin1')
# data_2022 = pd.read_excel(os.path.join('data',"resultats-par-niveau-burvot-t1-france-entiere_2022.xlsx"))
data_2022 = pd.read_csv(os.path.join('data',"elections-france-presidentielles-2022-1er-tour-par-bureau-de-vote.csv"),sep=';')

C:\Users\32mor\AppData\Local\Temp\ipykernel_2296\2565658940.py:3: DtypeWarning: Columns (0,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  data_2022 = pd.read_csv(os.path.join('data',"elections-france-presidentielles-2022-1er-tour-par-bureau-de-vote.csv"),sep=';')

In [3]:
data_2017 = pd.read_csv(config.path_2017)
data_2017 = pd.read_csv(os.path.join('data','PR17_BVot_T1_FE.txt'),sep=';',encoding='latin1')

C:\Users\32mor\AppData\Local\Temp\ipykernel_2296\658559355.py:2: DtypeWarning: Columns (0,6) have mixed types. Specify dtype option on import or set low_memory=False.
  data_2017 = pd.read_csv(os.path.join('data','PR17_BVot_T1_FE.txt'),sep=';',encoding='latin1')

In [4]:
data_2017_first_half = data_2017.index.to_frame().reset_index()
data_2017_second_half = data_2017.reset_index(drop=True)

In [5]:
columns_infos = ['Code du département', 'Libellé du département',
'Code de la circonscription', 'Libellé de la circonscription',
'Code de la commune', 'Libellé de la commune', 'Code du b.vote',
'Inscrits', 'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins',
'Blancs', '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins',
'% Nuls/Vot', 'Exprimés', '% Exp/Ins', '% Exp/Vot', ]
columns_to_be_repeated = ['N°Panneau', 'Sexe','Nom', 'Prénom', 'Voix', '% Voix/Ins', '% Voix/Exp']
data_2017_second_half.columns = [i for i in range(70,70+data_2017_second_half.shape[1])]
data_final_2017 = pd.concat([data_2017_first_half, data_2017_second_half],axis=1)

In [6]:
number_repeats = (data_final_2017.shape[1] - len(columns_infos))/len(columns_to_be_repeated)

In [7]:
data_final_2017.columns = columns_infos + [f'{element}_{i}'for i in range(1,int(number_repeats)+1) for element in columns_to_be_repeated ]

In [8]:
df_2017  = pd.DataFrame(columns=columns_infos+columns_to_be_repeated)
n=0
for i in range(int(number_repeats)):
    n = len(columns_infos)+(i)*len(columns_to_be_repeated)
    indexes = [i for i in range(len(columns_infos))] + [i for i in range(n,n+len(columns_to_be_repeated))]
    data = data_final_2017.iloc[:,indexes]
    data.columns = columns_infos+columns_to_be_repeated
    df_2017 = pd.concat([df_2017, data])

In [16]:
df_2017['Libellé de la commune'].nunique()

33363

In [48]:
df_revenus = pd.read_csv(os.path.join('data',"indic-struct-distrib-revenu-2019-COMMUNES","FILO2019_DISP_COM.csv"),sep=";")

C:\Users\32mor\AppData\Local\Temp\ipykernel_2296\1833202794.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_revenus = pd.read_csv(os.path.join('data',"indic-struct-distrib-revenu-2019-COMMUNES","FILO2019_DISP_COM.csv"),sep=";")

In [49]:
df_communes = pd.read_csv(os.path.join('data',"commune","commune2021.csv"))

In [50]:
def proper_codgeo(element):
    element = str(element)
    if len(element)<5:
        element = f'{0}{element}'
    return element

In [55]:
df_communes["CODGEO"] = df_communes['COM'].apply(proper_codgeo)
df_revenus["CODGEO"] = df_revenus['CODGEO'].apply(proper_codgeo)
df_revenus = df_revenus.merge(df_communes[["CODGEO","LIBELLE"]],on="CODGEO")

,CODGEO,NBMEN19,NBPERS19,NBUC19,Q119,Q219,Q319,Q3_Q1,D119,D219,...,OPR6PCHO19,OPR6PBEN19,OPR6PPEN19,OPR6PPAT19,OPR6PPSOC19,OPR6PPFAM19,OPR6PPMINI19,OPR6PPLOGT19,OPR6PIMPOT19,LIBELLE
0,01001,322,819,542.7,NaN,23970,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L'Abergement-Clémenciat
1,01002,113,263,177.2,NaN,23640,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L'Abergement-de-Varey
2,01004,6711,15040,10296.8,14940.0,20510,27310.0,12370.0,11080.0,13800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ambérieu-en-Bugey
3,01005,720,1823,1204.3,NaN,24050,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ambérieux-en-Dombes
4,01007,1160,2853,1888.8,18560.0,23380,29570.0,11020.0,14360.0,17450.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ambronay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31973,97420,8339,23843,15047.6,11270.0,16710,24620.0,13350.0,8630.0,10480.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sainte-Suzanne
31974,97421,2463,6927,4399.9,8960.0,12340,17250.0,8300.0,6540.0,8330.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Salazie
31975,97422,30048,77963,50710.5,10790.0,15320,23210.0,12430.0,8140.0,10050.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Le Tampon
31976,97423,2418,6982,4436.6,10820.0,15750,22410.0,11590.0,8280.0,10080.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Les Trois-Bassins
31977,97424,2121,5488,3598.9,9710.0,12980,18280.0,8570.0,7080.0,9080.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cilaos